# Generated by Django 2.2.2 on 2019-10-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wish_List', models.CharField(max_length=30)),
                ('Date', models.DateTimeField(null=True)),
            ],
        ),
    ]
